### ISSUE TITLE
suppressing initial message

### ISSUE THREAD

**Issue by mg64ve** [tlolkema/RobotNotifications#1]
Hello, I am new to this library and robot framework.
I am using the example in the readme.
Is it possible to suppress the initial message: "Testing has started!" and how ?
I would like to get only alert messages.
Thanks.

**Comment by tlolkema** [comment]
Hi,

The first argument to the "Post Message To Channel" keyword contains the markdown formatted text. The given example just shows how you can use your own messages or use Robot Framework variables. If you only like to get alert messages delete the "Start Suite" keyword from the example.

Let me know if you get stuck and i'll help you out!
